config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name,:address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit,:destroy, :update]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews.order(created_at: :desc)
    @review = Review.new #Para funcione o form do review dentro do show do restaurant
    @total_reviews = @reviews.count
    @rating_average = @reviews.average(:rating)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(check_params_restaurant)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(check_params_restaurant)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def check_params_restaurant
    params.require(:restaurant).permit(:category,:name,:phone_number ,:address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :new, :create, :destroy]

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(check_params_review)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @review.destroy
  end

  private

  def check_params_review
    params.require(:review).permit(:content,:rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>My restaurant review MVP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <%= render './navbar'%>
  </header>
  <body>
    <div class="wrapper">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- [...] all the fields -->

  <%= f.input :name %>
  <%= f.input :category, collection: %w[chinese italian japanese french belgian]  %>
  <%= f.input :phone_number %>
  <%= f.input :address %>
  <%= f.submit  class: "btn btn-success btn-lg" %>
  <%= link_to 'Back', restaurants_path, class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant details</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Check out our Restaurants</h1>


<table class='table'>
  <tr>
    <th>Name</th>
    <th>Cuisine</th>
    <th>See</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @restaurants.each do |restaurant| %>
  <tr>
    <td>
      <%= restaurant.name %>
    </td>
    <td>
      <%= restaurant.category %>
    </td>
    <td>
       <%= link_to '', restaurant_path(restaurant), class: 'fas fa-eye fa-lg' %>
    </td>
    <td>
      <%= link_to '', edit_restaurant_path(restaurant), class: 'far fa-edit fa-lg' %>
    </td>
    <td>
      <%= link_to '', restaurant_path(restaurant),method: :delete, data: { confirm: "Are you sure?" }, class: 'far fa-trash-alt fa-lg' %>
    </td>
  </tr>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<h1>Add a new Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3>
  <i class="fas fa-utensils fa-xs"></i>
  <%= @restaurant.category %>
</h3>
<h3>
  <i class="fas fa-phone fa-xs"></i>
  <%= @restaurant.phone_number %>
</h3>
<h3>
  <i class="fas fa-map-marker fa-xs"></i>
  <%= @restaurant.address %>
</h3>
<p class='action-option-icons'>
  <%= link_to '', edit_restaurant_path(@restaurant), class: 'far fa-edit fa-lg' %>
  <%= link_to '', restaurant_path(@restaurant),method: :delete, data: { confirm: "Are you sure?" }, class: 'far fa-trash-alt fa-lg' %>
</p>

<div class="text-standout">
  <% if @reviews.count.positive? %>
      <h2>
        Average Rating: <%= @rating_average %>
      </h2>
      <h2>
        Total reviews: <%= @total_reviews %>
      </h2>
      <% else %>
      <h2>
        Be the first to review this restaurant
      </h2>
  <% end %>
</div>


<h3>Add your review </h3>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :content, as: :text  %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
  <%= f.submit "Add review", class: "btn btn-success btn-lg" %>
  <%= link_to 'Back', restaurants_path, class: 'btn btn-primary btn-lg' %>
<% end %>

<div class="review-card">
  <h3><%= @reviews.count.positive? ? "Reviews for #{@restaurant.name}" : '' %></h3>
  <% if @reviews.count.positive? %>
    <table class='table'>
      <tr>
        <th>
          Comments
        </th>
        <th>
          Rating
        </th>
      </tr>
      <% @reviews.each do |review| %>
      <tr>
        <td>
          <%= review.content %>
        </td>
        <td>
          <%= review.rating %>
        </td>
      </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Share your review at <%= @restaurant.name %></h1>


<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :content, as: :text  %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
  <%= f.submit "add a review", class: "btn btn-success btn-lg" %>
  <%= link_to 'Back', restaurant_path(@restaurant), class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>